/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VendorType =
  | 'Profile'
  | 'Hardware'
  | 'Metall'
  | 'Glass'
  | 'Spacer'
  | 'Glazing'
  | 'Panel';
export type LocaleString =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
/**
 * --- Как описать типы на разных языках ???
 */
export type ProfileType =
  | 'Frame'
  | 'Sash'
  | 'Mullion'
  | 'GlazingBead'
  | 'Reinforcement'
  | 'PseudoMullion'
  | 'Connector';
/**
 * -- Материал дистанционной рамки, см. например https://www.glastory.net/insulating-glass-spacers-all-you-wanted-to-know/ и https://glazingmag.ru/distantsionnaya-ramka-dlya-steklopaketa-vidy-i-naznachenie/ и https://okna-blitz.ru/drugoe/distantsionnye-ramki-dlya-steklopaketov-razmery-i-vidy.html
 */
export type SpacerMaterial =
  | 'Aluminum'
  | 'Warm edge'
  | 'Stainless steel warm edge'
  | 'Plastic-metal hybrid warm edge'
  | 'Flexible warm edge'
  | 'TPS';
/**
 * -- Тип стекла, ниже из классификации по https://www.doubleglazingnetwork.com/blog/window-glass-types/
 */
export type GlassType =
  | 'Float Glass'
  | 'Laminated Safety Glass'
  | 'Obscured Glass'
  | 'Tinted Glass'
  | 'Tempered Glass'
  | 'Insulated Glass'
  | 'Mirrored Glass'
  | 'Low-E Glass'
  | 'Wired Glass';
export type ComponentFeatures =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type CuttingType = 'Angle45' | 'Vertical' | 'Horizontal' | 'Square';
/**
 * -- Тип кодирования цвета (классификатор)
 */
export type ColorType = 'PVC' | 'Renolit' | 'RAL';

/**
 * Order in Windows Branch
 */
export interface Order {
  openwinversion: string;
  info: Info;
  /**
   * --- ранее order_data
   */
  definitions?: {
    /**
     * Дата заказа
     */
    data?: string;
    /**
     * Заказчик
     */
    customer?: string;
    /**
     * --- Зачем ?
     */
    specification?: string;
    [k: string]: unknown;
  };
  dictionaries?: Dictionaries;
  /**
   * --- Альтернативно items, apertures, component, RoughOpening, определить что первично, конструкция или проем
   */
  constructions?: Construction[];
  [k: string]: unknown;
}
export interface Info {
  id: string;
  locale?: string;
  [k: string]: unknown;
}
export interface Dictionaries {
  sync?: boolean;
  vendors?: Vendor[];
  profileSystems?: ProfileSystem[];
  profiles?: Profile[];
  reinforcement?: Reinforcement[];
  spacer?: Spacer[];
  glasses?: Glass[];
  glazing?: Glazing[];
  panel?: Panel[];
  [k: string]: unknown;
}
export interface Vendor {
  id?: number;
  vendorType?: VendorType;
  name: LocaleString;
  web?: string;
  [k: string]: unknown;
}
export interface ProfileSystem {
  id: number;
  vendorId: number;
  name: string;
  [k: string]: unknown;
}
/**
 * --- Описываем армирование здесь?
 */
export interface Profile {
  id: number;
  vendorArticle: VendorMaterial;
  profileType: ProfileType;
  profileSystemId?: number;
  a?: number;
  b?: number;
  c?: number;
  d?: number;
  e?: number;
  w?: number;
  w1?: number;
  w2?: number;
  h?: number;
  h1?: number;
  [k: string]: unknown;
}
export interface VendorMaterial {
  vendorId: number;
  /**
   * --- Название !!!
   */
  article: string;
  name?: string;
  [k: string]: unknown;
}
/**
 * --- Или армирование описываем отдельно ???
 */
export interface Reinforcement {
  id: number;
  vendorArticle: VendorMaterial;
  ix?: number;
  iy?: number;
  h?: number;
  h1?: number;
  weight?: number;
  [k: string]: unknown;
}
/**
 * -- Дистанционная рамка
 */
export interface Spacer {
  id?: number;
  vendorArticle?: VendorMaterial;
  /**
   * -- Ширина рамки
   */
  size?: number;
  material?: SpacerMaterial;
  /**
   * -- Толщина стенки
   */
  thickness?: number;
  /**
   * Вес 1 п.м.
   */
  weight?: number;
  [k: string]: unknown;
}
/**
 * -- Стекло, характеристики Lt-Ug см. например https://www.agc-yourglass.com/en-UK/brands/energy
 */
export interface Glass {
  id?: number;
  vendorArticle?: VendorMaterial;
  glassType: GlassType;
  thickness: number;
  /**
   * -- Вес 1 м2
   */
  weight?: number;
  Lt?: number;
  Sf?: number;
  Lr?: number;
  Ug?: number;
  [k: string]: unknown;
}
export interface Glazing {
  id?: number;
  vendorArticle?: VendorMaterial;
  thickness?: number;
  glasses?: Glass[];
  spacer?: Spacer[];
  [k: string]: unknown;
}
/**
 * -- Заполнения
 */
export interface Panel {
  id?: number;
  vendorArticle?: VendorMaterial;
  /**
   * -- Вводим тип панели?
   */
  panelType?: string;
  thickness: number;
  /**
   * -- Вес 1 м2
   */
  weight?: number;
  [k: string]: unknown;
}
/**
 * Конструкция в заказе
 */
export interface Construction {
  id: number;
  /**
   * --- Проем в заказе
   */
  roughOpening?: {
    id?: number;
    sides?: Segment[];
    /**
     * замкнут ли периметр
     */
    closed?: boolean;
    [k: string]: unknown;
  };
  /**
   * --- Список элементов (products, components etc.) в конструкции, ex products
   */
  elements?: Element[];
  /**
   * --- Список соединетелей элементов конструкции
   */
  connections?: Connection[];
  [k: string]: unknown;
}
/**
 * Описание геометрического отрезка 3D для проволочной модели
 */
export interface Segment {
  id?: number;
  start: Point;
  end: Point;
  arcHeight?: number;
  [k: string]: unknown;
}
/**
 * --- Описание геометрической точки 3D, если координата отсутствует то она равно 0, поэтому убрали required
 */
export interface Point {
  /**
   * --- Добавлено для возможности ссылки на объект
   */
  id?: number;
  x?: number;
  y?: number;
  z?: number;
  [k: string]: unknown;
}
/**
 * --- Элемент конструкции
 */
export interface Element {
  id: number;
  /**
   * --- Тип элемента
   */
  elementType?: 'Window' | 'Door';
  profileSystemId?: number;
  geometry: Polygon[];
  /**
   * --- ex segments
   */
  splitters?: Segment[];
  components?: Component[];
  [k: string]: unknown;
}
/**
 * Полигон в 3D
 */
export interface Polygon {
  id?: number;
  sides?: Segment[];
  /**
   * замкнут ли периметр
   */
  closed?: boolean;
  [k: string]: unknown;
}
export interface Component {
  /**
   * --- ex element_type
   */
  componentType?: 'Frame' | 'Sash' | 'Mullion' | 'Filling';
  features?: ComponentFeatures;
  /**
   * --- ex poligon_id
   */
  geometryId?: number;
  /**
   * --- ссылка на геометрию сплиттера, как это объединить с geometryId ?
   */
  splitterId?: number;
  /**
   * --- если применяется для всех балок компонента
   */
  profileId?: number;
  /**
   * --- ex profile_polygon
   */
  beams?: Beam[];
  /**
   * --- ex product_elements
   */
  components?: Component[];
  [k: string]: unknown;
}
/**
 * --- Балка профиля
 */
export interface Beam {
  /**
   * --- Ссылка на профиль из справочника
   */
  profileId?: number;
  cuttings?: BeamCuttings;
  /**
   * тип дренажирования на балке
   */
  drain?: 'NotAvailable' | 'Available' | 'Hidden';
  /**
   * наличие компенсационных отверстий на балке
   */
  compensationHole?: boolean;
  /**
   * -- цвет основы (для ПВХ)
   */
  baseColor?: {
    colorId: number;
    colorName: string;
    colorCode: string;
    colorType: ColorType;
    [k: string]: unknown;
  };
  /**
   * -- цвет ламинации/покраски изнутри/сверху
   */
  internalColor?: {
    colorId: number;
    colorName: string;
    colorCode: string;
    colorType: ColorType;
    [k: string]: unknown;
  };
  /**
   * -- цвет ламинации/покраски снаружи
   */
  externalColor?: {
    colorId: number;
    colorName: string;
    colorCode: string;
    colorType: ColorType;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface BeamCuttings {
  start_ext?: CuttingType;
  start_int?: CuttingType;
  end_ext?: CuttingType;
  end_int?: CuttingType;
  [k: string]: unknown;
}
/**
 * --- Описание сединителя элементов конструкции
 */
export interface Connection {
  id?: number;
  geometry?: Segment;
  profileId?: number;
  cutting?: BeamCuttings;
  [k: string]: unknown;
}
